//
// Generated file, do not edit! Created by opp_msgc 4.2 from Payload.msg.
//

#ifndef _PAYLOAD_M_H_
#define _PAYLOAD_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>Payload.msg</tt> by opp_msgc.
 * <pre>
 * packet Payload {
 *     int DST;
 *     int SRC;
 *     string SessionId;
 *     string PacketId;
 *     int Class;
 * }
 * </pre>
 */
class Payload : public ::cPacket
{
  protected:
    int DST_var;
    int SRC_var;
    opp_string SessionId_var;
    opp_string PacketId_var;
    int Class_var;

  private:
    void copy(const Payload& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const Payload&);

  public:
    Payload(const char *name=NULL, int kind=0);
    Payload(const Payload& other);
    virtual ~Payload();
    Payload& operator=(const Payload& other);
    virtual Payload *dup() const {return new Payload(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual int getDST() const;
    virtual void setDST(int DST);
    virtual int getSRC() const;
    virtual void setSRC(int SRC);
    virtual const char * getSessionId() const;
    virtual void setSessionId(const char * SessionId);
    virtual const char * getPacketId() const;
    virtual void setPacketId(const char * PacketId);
    virtual int getClass() const;
    virtual void setClass(int Class);
};

inline void doPacking(cCommBuffer *b, Payload& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, Payload& obj) {obj.parsimUnpack(b);}


#endif // _PAYLOAD_M_H_
